//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 11:40:09 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "rentacar", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rentacar;
