//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 11:40:09 AM CEST 
//


package rentacar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="korisnik" type="{rentacar}Korisnik"/>
 *         &lt;element name="datum_od" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="datum_do" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element ref="{rentacar}Automobil"/>
 *         &lt;element name="rezervacija_agent" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="status" type="{rentacar}StatusRezervacije"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "korisnik",
    "datumOd",
    "datumDo",
    "automobil",
    "rezervacijaAgent",
    "status"
})
@XmlRootElement(name = "Rezervacija")
public class Rezervacija {

    protected long id;
    @XmlElement(required = true)
    protected Korisnik korisnik;
    @XmlElement(name = "datum_od", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumOd;
    @XmlElement(name = "datum_do", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumDo;
    @XmlElement(name = "Automobil", required = true)
    protected Automobil automobil;
    @XmlElement(name = "rezervacija_agent")
    protected boolean rezervacijaAgent;
    @XmlElement(required = true)
    protected StatusRezervacije status;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the korisnik property.
     * 
     * @return
     *     possible object is
     *     {@link Korisnik }
     *     
     */
    public Korisnik getKorisnik() {
        return korisnik;
    }

    /**
     * Sets the value of the korisnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Korisnik }
     *     
     */
    public void setKorisnik(Korisnik value) {
        this.korisnik = value;
    }

    /**
     * Gets the value of the datumOd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumOd() {
        return datumOd;
    }

    /**
     * Sets the value of the datumOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumOd(XMLGregorianCalendar value) {
        this.datumOd = value;
    }

    /**
     * Gets the value of the datumDo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumDo() {
        return datumDo;
    }

    /**
     * Sets the value of the datumDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumDo(XMLGregorianCalendar value) {
        this.datumDo = value;
    }

    /**
     * Gets the value of the automobil property.
     * 
     * @return
     *     possible object is
     *     {@link Automobil }
     *     
     */
    public Automobil getAutomobil() {
        return automobil;
    }

    /**
     * Sets the value of the automobil property.
     * 
     * @param value
     *     allowed object is
     *     {@link Automobil }
     *     
     */
    public void setAutomobil(Automobil value) {
        this.automobil = value;
    }

    /**
     * Gets the value of the rezervacijaAgent property.
     * 
     */
    public boolean isRezervacijaAgent() {
        return rezervacijaAgent;
    }

    /**
     * Sets the value of the rezervacijaAgent property.
     * 
     */
    public void setRezervacijaAgent(boolean value) {
        this.rezervacijaAgent = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusRezervacije }
     *     
     */
    public StatusRezervacije getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusRezervacije }
     *     
     */
    public void setStatus(StatusRezervacije value) {
        this.status = value;
    }

}
