//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 05:39:18 PM CEST 
//


package xml.glavni_deo.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element ref="{korisnik}Agent"/>
 *         &lt;element name="Pick_up_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Drop_off_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Booking_status" type="{korisnik}Booking_status"/>
 *         &lt;element ref="{korisnik}Automobili"/>
 *         &lt;element ref="{korisnik}Izvestaji"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "agent",
    "pickUpDate",
    "dropOffDate",
    "bookingStatus",
    "automobili",
    "izvestaji"
})
@XmlRootElement(name = "AgentBooking")
public class AgentBooking {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "Agent", required = true)
    protected Agent agent;
    @XmlElement(name = "Pick_up_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar pickUpDate;
    @XmlElement(name = "Drop_off_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dropOffDate;
    @XmlElement(name = "Booking_status", required = true)
    protected BookingStatus bookingStatus;
    @XmlElement(name = "Automobili", required = true)
    protected Automobili automobili;
    @XmlElement(name = "Izvestaji", required = true)
    protected Izvestaji izvestaji;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link Agent }
     *     
     */
    public Agent getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agent }
     *     
     */
    public void setAgent(Agent value) {
        this.agent = value;
    }

    /**
     * Gets the value of the pickUpDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPickUpDate() {
        return pickUpDate;
    }

    /**
     * Sets the value of the pickUpDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPickUpDate(XMLGregorianCalendar value) {
        this.pickUpDate = value;
    }

    /**
     * Gets the value of the dropOffDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDropOffDate() {
        return dropOffDate;
    }

    /**
     * Sets the value of the dropOffDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDropOffDate(XMLGregorianCalendar value) {
        this.dropOffDate = value;
    }

    /**
     * Gets the value of the bookingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BookingStatus }
     *     
     */
    public BookingStatus getBookingStatus() {
        return bookingStatus;
    }

    /**
     * Sets the value of the bookingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingStatus }
     *     
     */
    public void setBookingStatus(BookingStatus value) {
        this.bookingStatus = value;
    }

    /**
     * Gets the value of the automobili property.
     * 
     * @return
     *     possible object is
     *     {@link Automobili }
     *     
     */
    public Automobili getAutomobili() {
        return automobili;
    }

    /**
     * Sets the value of the automobili property.
     * 
     * @param value
     *     allowed object is
     *     {@link Automobili }
     *     
     */
    public void setAutomobili(Automobili value) {
        this.automobili = value;
    }

    /**
     * Gets the value of the izvestaji property.
     * 
     * @return
     *     possible object is
     *     {@link Izvestaji }
     *     
     */
    public Izvestaji getIzvestaji() {
        return izvestaji;
    }

    /**
     * Sets the value of the izvestaji property.
     * 
     * @param value
     *     allowed object is
     *     {@link Izvestaji }
     *     
     */
    public void setIzvestaji(Izvestaji value) {
        this.izvestaji = value;
    }

}
