//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 05:39:20 PM CEST 
//


package xml.glavni_deo.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CTModelAuta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTModelAuta">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Ime_modela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Marka" type="{korisnik}CTMarkaAuta"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTModelAuta", propOrder = {
    "id",
    "imeModela",
    "marka"
})
public class CTModelAuta {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "Ime_modela", required = true)
    protected String imeModela;
    @XmlElement(name = "Marka", required = true)
    protected CTMarkaAuta marka;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the imeModela property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeModela() {
        return imeModela;
    }

    /**
     * Sets the value of the imeModela property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeModela(String value) {
        this.imeModela = value;
    }

    /**
     * Gets the value of the marka property.
     * 
     * @return
     *     possible object is
     *     {@link CTMarkaAuta }
     *     
     */
    public CTMarkaAuta getMarka() {
        return marka;
    }

    /**
     * Sets the value of the marka property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTMarkaAuta }
     *     
     */
    public void setMarka(CTMarkaAuta value) {
        this.marka = value;
    }

}
