//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 05:39:16 PM CEST 
//


package xml.glavni_deo.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element ref="{korisnik}Automobil"/>
 *         &lt;element name="Slobodno_od" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Slobodno_do" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element ref="{korisnik}Korisnik"/>
 *         &lt;element ref="{korisnik}Cenovnik"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "automobil",
    "slobodnoOd",
    "slobodnoDo",
    "korisnik",
    "cenovnik"
})
@XmlRootElement(name = "Oglas")
public class Oglas {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "Automobil", required = true)
    protected Automobil automobil;
    @XmlElement(name = "Slobodno_od", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar slobodnoOd;
    @XmlElement(name = "Slobodno_do", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar slobodnoDo;
    @XmlElement(name = "Korisnik", required = true)
    protected Korisnik korisnik;
    @XmlElement(name = "Cenovnik", required = true)
    protected Cenovnik cenovnik;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the automobil property.
     * 
     * @return
     *     possible object is
     *     {@link Automobil }
     *     
     */
    public Automobil getAutomobil() {
        return automobil;
    }

    /**
     * Sets the value of the automobil property.
     * 
     * @param value
     *     allowed object is
     *     {@link Automobil }
     *     
     */
    public void setAutomobil(Automobil value) {
        this.automobil = value;
    }

    /**
     * Gets the value of the slobodnoOd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSlobodnoOd() {
        return slobodnoOd;
    }

    /**
     * Sets the value of the slobodnoOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSlobodnoOd(XMLGregorianCalendar value) {
        this.slobodnoOd = value;
    }

    /**
     * Gets the value of the slobodnoDo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSlobodnoDo() {
        return slobodnoDo;
    }

    /**
     * Sets the value of the slobodnoDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSlobodnoDo(XMLGregorianCalendar value) {
        this.slobodnoDo = value;
    }

    /**
     * Gets the value of the korisnik property.
     * 
     * @return
     *     possible object is
     *     {@link Korisnik }
     *     
     */
    public Korisnik getKorisnik() {
        return korisnik;
    }

    /**
     * Sets the value of the korisnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Korisnik }
     *     
     */
    public void setKorisnik(Korisnik value) {
        this.korisnik = value;
    }

    /**
     * Gets the value of the cenovnik property.
     * 
     * @return
     *     possible object is
     *     {@link Cenovnik }
     *     
     */
    public Cenovnik getCenovnik() {
        return cenovnik;
    }

    /**
     * Sets the value of the cenovnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cenovnik }
     *     
     */
    public void setCenovnik(Cenovnik value) {
        this.cenovnik = value;
    }

}
