version: "3.7"
services:

  authentication-service:
    image: authentication-service
    restart: on-failure
    container_name: authentication-service
    tty: true
    build: 
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - 9100:9100
    networks:
      - xml
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: xml
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mysql
      - eureka-server

  car-service:
    image: car-service
    restart: on-failure
    container_name: car-service
    tty: true
    build: 
      context: ./car-service
      dockerfile: Dockerfile
    ports:
      - 8600:8600
    networks:
      - xml
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: xml
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mysql
      - eureka-server

  message-service:
    image: message-service
    restart: on-failure
    container_name: message-service
    tty: true
    build: 
      context: ./message-service
      dockerfile: Dockerfile
    ports:
      - 8900:8900
    networks:
      - xml
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: xml
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mysql
      - eureka-server

  rating-service:
    image: rating-service
    restart: on-failure
    container_name: rating-service
    tty: true
    build: 
      context: ./rating-service
      dockerfile: Dockerfile
    ports:
      - 8700:8700
    networks:
      - xml
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: xml
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mysql
      - eureka-server

  rent-service:
    image: rent-service
    restart: on-failure
    container_name: rent-service
    tty: true
    build: 
      context: ./rent-service
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    networks:
      - xml
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: xml
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mysql
      - eureka-server

  search-service:
    image: search-service
    restart: on-failure
    container_name: search-service
    tty: true
    build: 
      context: ./search-service
      dockerfile: Dockerfile
    ports:
      - 8800:8800
    networks:
      - xml
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: xml
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mysql
      - eureka-server

  mysql:
    image: mysql:8.0.19
    restart: always
    container_name: mysql
    ports:
      - 3306
    networks:
      - xml
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: xml
    volumes:
      - mysql-data:/var/lib/mysql

  eureka-server:
    image: eureka-server
    restart: on-failure
    container_name: eureka-server
    tty: true
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports: 
      - 8761:8761
    networks: 
      - xml
    environment: 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  zuul-gateway-service:
    image: zuul-gateway-service
    restart: on-failure
    container_name: zuul-gateway-service
    tty: true
    build:
      context: ./zuul-gateway-service
      dockerfile: Dockerfile
    ports: 
      - 8762:8762
    networks: 
      - xml
    environment: 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

volumes:
  mysql-data:

networks:
  xml:
    name: xml
    driver: bridge
   

