//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 11:40:09 AM CEST 
//

package com.rentacar.backend.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Adresa complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Adresa">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="drzava" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Adresa", propOrder = { "ulica", "broj", "mesto", "drzava" })
@Entity
@Table(name = "adresa")
public class Adresa {

	@XmlElement(required = true)
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	protected Long id;
	@XmlElement(required = true)
	protected String ulica;
	@XmlElement(required = true)
	protected String broj;
	@XmlElement(required = true)
	protected String mesto;
	@XmlElement(required = true)
	protected String drzava;

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public Long getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(Long value) {
		this.id = value;
	}

	/**
	 * Gets the value of the ulica property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUlica() {
		return ulica;
	}

	/**
	 * Sets the value of the ulica property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setUlica(String value) {
		this.ulica = value;
	}

	/**
	 * Gets the value of the broj property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBroj() {
		return broj;
	}

	/**
	 * Sets the value of the broj property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBroj(String value) {
		this.broj = value;
	}

	/**
	 * Gets the value of the mesto property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMesto() {
		return mesto;
	}

	/**
	 * Sets the value of the mesto property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setMesto(String value) {
		this.mesto = value;
	}

	/**
	 * Gets the value of the drzava property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDrzava() {
		return drzava;
	}

	/**
	 * Sets the value of the drzava property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDrzava(String value) {
		this.drzava = value;
	}

}
