//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 05:39:20 PM CEST 
//


package korisnik;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Cena_po_danu" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Cena_po_km" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Cena_za_CDW" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "cenaPoDanu",
    "cenaPoKm",
    "cenaZaCDW"
})
@XmlRootElement(name = "Cenovnik")
public class Cenovnik {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "Cena_po_danu")
    protected float cenaPoDanu;
    @XmlElement(name = "Cena_po_km")
    protected float cenaPoKm;
    @XmlElement(name = "Cena_za_CDW")
    protected float cenaZaCDW;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the cenaPoDanu property.
     * 
     */
    public float getCenaPoDanu() {
        return cenaPoDanu;
    }

    /**
     * Sets the value of the cenaPoDanu property.
     * 
     */
    public void setCenaPoDanu(float value) {
        this.cenaPoDanu = value;
    }

    /**
     * Gets the value of the cenaPoKm property.
     * 
     */
    public float getCenaPoKm() {
        return cenaPoKm;
    }

    /**
     * Sets the value of the cenaPoKm property.
     * 
     */
    public void setCenaPoKm(float value) {
        this.cenaPoKm = value;
    }

    /**
     * Gets the value of the cenaZaCDW property.
     * 
     */
    public float getCenaZaCDW() {
        return cenaZaCDW;
    }

    /**
     * Sets the value of the cenaZaCDW property.
     * 
     */
    public void setCenaZaCDW(float value) {
        this.cenaZaCDW = value;
    }

}
