//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 12:22:52 PM CEST 
//


package com.rentacar.agent.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rentacar package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rentacar
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Izvestaj }
     * 
     */
    public Izvestaj createIzvestaj() {
        return new Izvestaj();
    }

    /**
     * Create an instance of {@link Automobil }
     * 
     */
    public Automobil createAutomobil() {
        return new Automobil();
    }

    /**
     * Create an instance of {@link MarkaAuta }
     * 
     */
    public MarkaAuta createMarkaAuta() {
        return new MarkaAuta();
    }

    /**
     * Create an instance of {@link ModelAuta }
     * 
     */
    public ModelAuta createModelAuta() {
        return new ModelAuta();
    }

    /**
     * Create an instance of {@link KlasaAuta }
     * 
     */
    public KlasaAuta createKlasaAuta() {
        return new KlasaAuta();
    }

    /**
     * Create an instance of {@link VrstaGoriva }
     * 
     */
    public VrstaGoriva createVrstaGoriva() {
        return new VrstaGoriva();
    }

    /**
     * Create an instance of {@link TipMenjaca }
     * 
     */
    public TipMenjaca createTipMenjaca() {
        return new TipMenjaca();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link GetPorukaResponse }
     * 
     */
    public GetPorukaResponse createGetPorukaResponse() {
        return new GetPorukaResponse();
    }

    /**
     * Create an instance of {@link Poruka }
     * 
     */
    public Poruka createPoruka() {
        return new Poruka();
    }

    /**
     * Create an instance of {@link Korisnik }
     * 
     */
    public Korisnik createKorisnik() {
        return new Korisnik();
    }

    /**
     * Create an instance of {@link Rezervacija }
     * 
     */
    public Rezervacija createRezervacija() {
        return new Rezervacija();
    }

    /**
     * Create an instance of {@link GetRoleRequest }
     * 
     */
    public GetRoleRequest createGetRoleRequest() {
        return new GetRoleRequest();
    }

    /**
     * Create an instance of {@link GetAgentRequest }
     * 
     */
    public GetAgentRequest createGetAgentRequest() {
        return new GetAgentRequest();
    }

    /**
     * Create an instance of {@link SavePorukaRequest }
     * 
     */
    public SavePorukaRequest createSavePorukaRequest() {
        return new SavePorukaRequest();
    }

    /**
     * Create an instance of {@link Oglas }
     * 
     */
    public Oglas createOglas() {
        return new Oglas();
    }

    /**
     * Create an instance of {@link Cenovnik }
     * 
     */
    public Cenovnik createCenovnik() {
        return new Cenovnik();
    }

    /**
     * Create an instance of {@link GetAgentResponse }
     * 
     */
    public GetAgentResponse createGetAgentResponse() {
        return new GetAgentResponse();
    }

    /**
     * Create an instance of {@link GetkrajnjiKorisnikResponse }
     * 
     */
    public GetkrajnjiKorisnikResponse createGetkrajnjiKorisnikResponse() {
        return new GetkrajnjiKorisnikResponse();
    }

    /**
     * Create an instance of {@link KrajnjiKorisnik }
     * 
     */
    public KrajnjiKorisnik createKrajnjiKorisnik() {
        return new KrajnjiKorisnik();
    }

    /**
     * Create an instance of {@link GetKrajnjiKorisnikRequest }
     * 
     */
    public GetKrajnjiKorisnikRequest createGetKrajnjiKorisnikRequest() {
        return new GetKrajnjiKorisnikRequest();
    }

    /**
     * Create an instance of {@link GetPorukaRequest }
     * 
     */
    public GetPorukaRequest createGetPorukaRequest() {
        return new GetPorukaRequest();
    }

    /**
     * Create an instance of {@link GetRoleResponse }
     * 
     */
    public GetRoleResponse createGetRoleResponse() {
        return new GetRoleResponse();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Komentar }
     * 
     */
    public Komentar createKomentar() {
        return new Komentar();
    }

    /**
     * Create an instance of {@link GetPrivilegeRequest }
     * 
     */
    public GetPrivilegeRequest createGetPrivilegeRequest() {
        return new GetPrivilegeRequest();
    }

    /**
     * Create an instance of {@link GetPrivilegeResponse }
     * 
     */
    public GetPrivilegeResponse createGetPrivilegeResponse() {
        return new GetPrivilegeResponse();
    }

    /**
     * Create an instance of {@link Privilege }
     * 
     */
    public Privilege createPrivilege() {
        return new Privilege();
    }

    /**
     * Create an instance of {@link SavePorukaResponse }
     * 
     */
    public SavePorukaResponse createSavePorukaResponse() {
        return new SavePorukaResponse();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link Administrator }
     * 
     */
    public Administrator createAdministrator() {
        return new Administrator();
    }

}
