//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 05:39:11 PM CEST 
//

package xml_bsep.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{korisnik}Korisnik"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "korisnik" })
@XmlRootElement(name = "Admin")
public class Admin {

	@XmlElement(name = "Korisnik", required = true)
	protected Korisnik korisnik;

	/**
	 * Gets the value of the korisnik property.
	 * 
	 * @return possible object is {@link Korisnik }
	 * 
	 */
	public Korisnik getKorisnik() {
		return korisnik;
	}

	/**
	 * Sets the value of the korisnik property.
	 * 
	 * @param value allowed object is {@link Korisnik }
	 * 
	 */
	public void setKorisnik(Korisnik value) {
		this.korisnik = value;
	}

}
