//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 05:39:20 PM CEST 
//


package xml_bsep.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the korisnik package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Model_QNAME = new QName("korisnik", "Model");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: korisnik
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Modeli }
     * 
     */
    public Modeli createModeli() {
        return new Modeli();
    }

    /**
     * Create an instance of {@link CTModelAuta }
     * 
     */
    public CTModelAuta createCTModelAuta() {
        return new CTModelAuta();
    }

    /**
     * Create an instance of {@link Izvestaj }
     * 
     */
    public Izvestaj createIzvestaj() {
        return new Izvestaj();
    }

    /**
     * Create an instance of {@link Automobil }
     * 
     */
    public Automobil createAutomobil() {
        return new Automobil();
    }

    /**
     * Create an instance of {@link CTMarkaAuta }
     * 
     */
    public CTMarkaAuta createCTMarkaAuta() {
        return new CTMarkaAuta();
    }

    /**
     * Create an instance of {@link CTKlasaAuta }
     * 
     */
    public CTKlasaAuta createCTKlasaAuta() {
        return new CTKlasaAuta();
    }

    /**
     * Create an instance of {@link CTVrstaGoriva }
     * 
     */
    public CTVrstaGoriva createCTVrstaGoriva() {
        return new CTVrstaGoriva();
    }

    /**
     * Create an instance of {@link CTTipMenjaca }
     * 
     */
    public CTTipMenjaca createCTTipMenjaca() {
        return new CTTipMenjaca();
    }

    /**
     * Create an instance of {@link Automobili }
     * 
     */
    public Automobili createAutomobili() {
        return new Automobili();
    }

    /**
     * Create an instance of {@link Izvestaji }
     * 
     */
    public Izvestaji createIzvestaji() {
        return new Izvestaji();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTModelAuta }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "korisnik", name = "Model")
    public JAXBElement<CTModelAuta> createModel(CTModelAuta value) {
        return new JAXBElement<CTModelAuta>(_Model_QNAME, CTModelAuta.class, null, value);
    }

}
