//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 05:39:20 PM CEST 
//


package korisnik;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Marka" type="{korisnik}CTMarkaAuta"/>
 *         &lt;element name="Model" type="{korisnik}CTModelAuta"/>
 *         &lt;element name="Klasa" type="{korisnik}CTKlasaAuta"/>
 *         &lt;element name="Gorivo" type="{korisnik}CTVrstaGoriva"/>
 *         &lt;element name="Menjac" type="{korisnik}CTTipMenjaca"/>
 *         &lt;element name="Kilometraza" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Dozvoljena_kilometraza" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CDW" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Decija_mesta" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Prosecna_ocena" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "marka",
    "model",
    "klasa",
    "gorivo",
    "menjac",
    "kilometraza",
    "dozvoljenaKilometraza",
    "cdw",
    "decijaMesta",
    "prosecnaOcena"
})
@XmlRootElement(name = "Automobil")
public class Automobil {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "Marka", required = true)
    protected CTMarkaAuta marka;
    @XmlElement(name = "Model", required = true)
    protected CTModelAuta model;
    @XmlElement(name = "Klasa", required = true)
    protected CTKlasaAuta klasa;
    @XmlElement(name = "Gorivo", required = true)
    protected CTVrstaGoriva gorivo;
    @XmlElement(name = "Menjac", required = true)
    protected CTTipMenjaca menjac;
    @XmlElement(name = "Kilometraza")
    protected long kilometraza;
    @XmlElement(name = "Dozvoljena_kilometraza")
    protected long dozvoljenaKilometraza;
    @XmlElement(name = "CDW")
    protected boolean cdw;
    @XmlElement(name = "Decija_mesta")
    protected int decijaMesta;
    @XmlElement(name = "Prosecna_ocena")
    protected float prosecnaOcena;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the marka property.
     * 
     * @return
     *     possible object is
     *     {@link CTMarkaAuta }
     *     
     */
    public CTMarkaAuta getMarka() {
        return marka;
    }

    /**
     * Sets the value of the marka property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTMarkaAuta }
     *     
     */
    public void setMarka(CTMarkaAuta value) {
        this.marka = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link CTModelAuta }
     *     
     */
    public CTModelAuta getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTModelAuta }
     *     
     */
    public void setModel(CTModelAuta value) {
        this.model = value;
    }

    /**
     * Gets the value of the klasa property.
     * 
     * @return
     *     possible object is
     *     {@link CTKlasaAuta }
     *     
     */
    public CTKlasaAuta getKlasa() {
        return klasa;
    }

    /**
     * Sets the value of the klasa property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTKlasaAuta }
     *     
     */
    public void setKlasa(CTKlasaAuta value) {
        this.klasa = value;
    }

    /**
     * Gets the value of the gorivo property.
     * 
     * @return
     *     possible object is
     *     {@link CTVrstaGoriva }
     *     
     */
    public CTVrstaGoriva getGorivo() {
        return gorivo;
    }

    /**
     * Sets the value of the gorivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTVrstaGoriva }
     *     
     */
    public void setGorivo(CTVrstaGoriva value) {
        this.gorivo = value;
    }

    /**
     * Gets the value of the menjac property.
     * 
     * @return
     *     possible object is
     *     {@link CTTipMenjaca }
     *     
     */
    public CTTipMenjaca getMenjac() {
        return menjac;
    }

    /**
     * Sets the value of the menjac property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTTipMenjaca }
     *     
     */
    public void setMenjac(CTTipMenjaca value) {
        this.menjac = value;
    }

    /**
     * Gets the value of the kilometraza property.
     * 
     */
    public long getKilometraza() {
        return kilometraza;
    }

    /**
     * Sets the value of the kilometraza property.
     * 
     */
    public void setKilometraza(long value) {
        this.kilometraza = value;
    }

    /**
     * Gets the value of the dozvoljenaKilometraza property.
     * 
     */
    public long getDozvoljenaKilometraza() {
        return dozvoljenaKilometraza;
    }

    /**
     * Sets the value of the dozvoljenaKilometraza property.
     * 
     */
    public void setDozvoljenaKilometraza(long value) {
        this.dozvoljenaKilometraza = value;
    }

    /**
     * Gets the value of the cdw property.
     * 
     */
    public boolean isCDW() {
        return cdw;
    }

    /**
     * Sets the value of the cdw property.
     * 
     */
    public void setCDW(boolean value) {
        this.cdw = value;
    }

    /**
     * Gets the value of the decijaMesta property.
     * 
     */
    public int getDecijaMesta() {
        return decijaMesta;
    }

    /**
     * Sets the value of the decijaMesta property.
     * 
     */
    public void setDecijaMesta(int value) {
        this.decijaMesta = value;
    }

    /**
     * Gets the value of the prosecnaOcena property.
     * 
     */
    public float getProsecnaOcena() {
        return prosecnaOcena;
    }

    /**
     * Sets the value of the prosecnaOcena property.
     * 
     */
    public void setProsecnaOcena(float value) {
        this.prosecnaOcena = value;
    }

}
